---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2025
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- name: Install exo service
  become: true
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name: libgl1
      vars:
       ansible_python_interpreter: /usr/bin/python3.10
    - name: Get the Python version
      set_fact:
        python_version: "{{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
    - block:
      - name: Add deadsnakes ppa
        ansible.builtin.apt_repository:
          repo: ppa:deadsnakes/ppa
      - name: Install dependencies
        ansible.builtin.package:
          name: python3.12
      - name: Select Python 3.12
        community.general.alternatives:
          name: python
          path: /usr/bin/python3.12
          link: /usr/bin/python3
      - name: Fix CNF Update DB file
        ansible.builtin.lineinfile:
          path: /usr/lib/cnf-update-db
          regexp: '^#!/usr/bin/python3'
          line: "#!/usr/bin/python{{ python_version }}"
      when: python_version is version('3.12', '<')
    - name: check to see if pip is already installed
      command: "pip --version"
      ignore_errors: true
      register: pip_is_installed
      changed_when: false
    - block:
       - name: download get-pip.py
         get_url:
           url: https://bootstrap.pypa.io/get-pip.py
           dest: /tmp
       - name: install pip
         command: "python3 /tmp/get-pip.py"
       - name: delete get-pip.py
         file:
           state: absent
           path: /tmp/get-pip.py
      when: pip_is_installed.rc != 0
    - name: Install exo binary
      ansible.builtin.pip:
        name: git+https://github.com/exo-explore/exo.git
    - name: Create the systemd service file
      copy:
        dest: /etc/systemd/system/exo.service
        content: |
          [Unit]
          Description=Exo Application
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/exo
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
    - name: Reload systemd to pick up the new service
      systemd:
        daemon_reload: yes
#    - name: Enable and start the service
#      systemd:
#        name: exo.service
#        enabled: yes
#        state: started
